set_property CFGBVS VCCO [current_design] 
set_property CONFIG_VOLTAGE 3.3 [current_design]
 
set_property IOSTANDARD LVCMOS33 [get_ports {clk}] 
set_property IOSTANDARD LVCMOS33 [get_ports {BTN}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN_RST}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_RST}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {act_seg[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx_busy]
 
 set_property PACKAGE_PIN W5 [get_ports {clk}]
create_clock -name main_clk -period 10 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN U18 [get_ports {BTN}]
set_property PACKAGE_PIN T17 [get_ports {BTN_RST}]
set_property PACKAGE_PIN L1 [get_ports {LED_RST}]

set_property PACKAGE_PIN P3 [get_ports {LED[0]}]
set_property PACKAGE_PIN U3 [get_ports {LED[1]}]
set_property PACKAGE_PIN W3 [get_ports {LED[2]}]

set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg[7]}]

set_property PACKAGE_PIN U2 [get_ports {act_seg[0]}]
set_property PACKAGE_PIN U4 [get_ports {act_seg[1]}]
set_property PACKAGE_PIN V4 [get_ports {act_seg[2]}]
set_property PACKAGE_PIN W4 [get_ports {act_seg[3]}]

set_property PACKAGE_PIN A18 [get_ports tx]
set_property PACKAGE_PIN E19 [get_ports tx_busy]
